apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-pushover-credentials
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: alertmanager-pushover-credentials   # same Secret name monitoring/release.yaml expects
    creationPolicy: Owner
  data:
    - secretKey: user_key
      remoteRef:
        key: "/pushover/USER_KEY"
    - secretKey: token
      remoteRef:
        key: "/pushover/TOKEN"
